# Embedded LDAP server configuration
spring.ldap.embedded.base-dn=dc=example,dc=org
spring.ldap.embedded.port=8389
spring.ldap.embedded.ldif=classpath:ldap-data.ldif
spring.ldap.embedded.validation.enabled=false

# LDAP connection
spring.ldap.urls=ldap://localhost:8389
spring.ldap.base=dc=example,dc=org
